// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjOJ0cNq_SIZ_qoFp6JVTMhnIkY6aaQZs',
    appId: '1:1050970392348:web:a4b5ace0bddd1bf0b1dcd9',
    messagingSenderId: '1050970392348',
    projectId: 'crafty-bay-app',
    authDomain: 'crafty-bay-app.firebaseapp.com',
    storageBucket: 'crafty-bay-app.firebasestorage.app',
    measurementId: 'G-B65ZCG31M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZvmBfNENVqSl-Oj3wax1a-dEfcmvq2jY',
    appId: '1:1050970392348:android:d725bacf78e74b27b1dcd9',
    messagingSenderId: '1050970392348',
    projectId: 'crafty-bay-app',
    storageBucket: 'crafty-bay-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rQPfvlvEOFM1W_zDviVGYhtvSXJJmTE',
    appId: '1:1050970392348:ios:c8254edf6daeefccb1dcd9',
    messagingSenderId: '1050970392348',
    projectId: 'crafty-bay-app',
    storageBucket: 'crafty-bay-app.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

}